### ISSUE TITLE
Use of ParserOutput::addModules  with non-array argument was deprecated in MediaWiki 1.38. 

### ISSUE THREAD

**Issue by sovello** [sigbertklinke/Iframe#8]
Use of ParserOutput::addModules 
with non-array argument was deprecated in MediaWiki 1.38. 
[Called from Iframe::renderIframe in Iframe/Iframe_body.php at line 192] 
in includes/debug/MWDebug.php  on line  381

**Comment by sovello** [comment]
@sigbertklinke  

The fix here will involve changing line 192 from 
`$parser->getOutput()->addModules( 'ext.Iframe' );`
to
`$parser->getOutput()->addModules( ["ext.Iframe"] );`

I already have a fix, let me know when I can make a PR.
It affects whoever upgrades to MW 1.39.1

**Comment by sigbertklinke** [comment]
ok, added your fix. thanks.
